server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: edge-service
    session:
      store-type: redis
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10
              burstCapacity: 20
              requestedTokens: 1
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: userService
                fallbackUri: forward:/users-fallback
            - name: Retry
              args:
                retries: 3
                method: GET
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms

      filter:
        request-rate-limiter:
          deny-empty-key: false

resilience4j:
  circuitbreaker:
    instances:
      userService:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        registerHealthIndicator: true
  timelimiter:
    instances:
      userService:
        timeoutDuration: 3s


